export const ROOM_CONNECTION_SUCCESS = 'ROOM_CONNECTION_SUCCESS';
export const ROOM_CONNECTION_FAIL = 'ROOM_CONNECTION_FAIL';
export const ROOM_CONNECTION_PENDING = 'ROOM_CONNECTION_PENDING';
export const ROOM_CONNECTION_DISCONNECTED = 'ROOM_CONNECTION_DISCONNECTED';

export const ROLE_USER = 'ROLE_USER';
export const ROLE_PEER = 'ROLE_PEER';
