export const SET_PREVIEW_TRACKS = 'SET_PREVIEW_TRACKS';
export const SET_PREVIEW_ERROR = 'SET_PREVIEW_ERROR';
export const SET_ROOM_CONNECTION_STATUS = 'SET_ROOM_CONNECTION_STATUS';
export const SET_EXTENSION_STATUS = 'SET_EXTENSION_STATUS';
export const SET_PARTICIPANT_TRACKS = 'SET_PARTICIPANT_TRACKS';
export const REMOVE_PREVIEW_TRACKS = 'REMOVE_PREVIEW_TRACKS';
export const SHARE_SCREEN = 'SHARE_SCREEN';
export const UNSHARE_SCREEN = 'UNSHARE_SCREEN';
