export const SET_PREVIEW_ERROR = 'SET_PREVIEW_ERROR';
export const SET_ROOM_CONNECTION_STATUS = 'SET_ROOM_CONNECTION_STATUS';
export const SET_EXTENSION_STATUS = 'SET_EXTENSION_STATUS';

export const SET_PEER = 'SET_PEER';
export const REMOVE_PEER = 'REMOVE_PEER';

export const SET_TRACKS = 'SET_TRACKS';
export const REMOVE_TRACKS = 'REMOVE_TRACKS';
export const REMOVE_TRACK = 'REMOVE_TRACK';

export const SHARE_SCREEN = 'SHARE_SCREEN';
export const UNSHARE_SCREEN = 'UNSHARE_SCREEN';
